// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMY6jq9Nq74ppI6-iVKWRyWtN4ypyzLrQ',
    appId: '1:750909210261:web:5342d72d0226a0fcc8259c',
    messagingSenderId: '750909210261',
    projectId: 'astrobase-4200d',
    authDomain: 'astrobase-4200d.firebaseapp.com',
    storageBucket: 'astrobase-4200d.appspot.com',
    measurementId: 'G-JQ94MECE03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT3RxNBdmOD_fe2gJhZjrCdxxrM8y0Vh0',
    appId: '1:750909210261:android:604212d5078356adc8259c',
    messagingSenderId: '750909210261',
    projectId: 'astrobase-4200d',
    storageBucket: 'astrobase-4200d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN4JKlkU3oRBkyKAveKP7X1mYyzaqfUU4',
    appId: '1:750909210261:ios:181270cfbdf46628c8259c',
    messagingSenderId: '750909210261',
    projectId: 'astrobase-4200d',
    storageBucket: 'astrobase-4200d.appspot.com',
    iosBundleId: 'com.example.astro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN4JKlkU3oRBkyKAveKP7X1mYyzaqfUU4',
    appId: '1:750909210261:ios:181270cfbdf46628c8259c',
    messagingSenderId: '750909210261',
    projectId: 'astrobase-4200d',
    storageBucket: 'astrobase-4200d.appspot.com',
    iosBundleId: 'com.example.astro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMY6jq9Nq74ppI6-iVKWRyWtN4ypyzLrQ',
    appId: '1:750909210261:web:6b6d65bc060b7965c8259c',
    messagingSenderId: '750909210261',
    projectId: 'astrobase-4200d',
    authDomain: 'astrobase-4200d.firebaseapp.com',
    storageBucket: 'astrobase-4200d.appspot.com',
    measurementId: 'G-3EZXKMCRFV',
  );
}
